version: "3.6"

services:

  postgres:
    image: postgres:15
    command: -E
    restart: always
    networks:
      - rss
    hostname: postgres
    ports:
      - "15432:5432"
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
      - ./.docker/postgres/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=rss
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user

networks:
  rss:
